# This is a basic workflow to help you get started with Actions

name: PR workflow
env:
  TEST_TAG: sansoucie/gdrf:test
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master,main,release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10']
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: test with tox
        run:
          tox

      - name: list files
        run: ls -l .
  docker:
      name: Docker
      if: github.event_name != 'pull_request'
      runs-on: ubuntu-latest
      steps:
          -   name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

          -   name: Check Out Repo
              uses: actions/checkout@v2

          -   name: Login to Github Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

          -   name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

          -   name: Build and export to Docker
              uses: docker/build-push-action@v2
              with:
                  context: .
                  load: true
                  tags: ${{ env.TEST_TAG }}
          -   name: Test
              run: |
                  docker run --rm ${{ env.TEST_TAG }}
